### ISSUE TITLE
Error when saving config settings

### ISSUE THREAD

**Issue by celexus** [fatfishdigital/zoommeeting#3]
When attempting to save the API settings the following error is displayed: 
![image (2)](https://user-images.githubusercontent.com/6831255/85750346-e7d05400-b709-11ea-96cb-db8fef052f5b.png)

**Comment by jasonleelab** [comment]
Can confirm.

**Comment by brandondeweese** [comment]
Getting same error....No movement on this at all?

**Comment by jasonleelab** [comment]
@brandondeweese I got it working but I had to modify the plugin. I know I changed /vendor/fatfish/zoom/src/models/Settings.php starting on line 41 (changed from 'required' to 'string'):
`public function rules()
    {
        return [
            ['Apikey', 'string'],
            ['ApiSecret', 'string'],
            ['HistoryToken', 'string'],
        ];
    }
`
I'm 90% sure I changed something else too, but I can't remember at the moment.

Hope that helps!

**Comment by fatfishdigital** [comment]
@brandondeweese Sorry for the trouble and late reply, is it possible to explain how you encounter those error. Are you saving empty endpoints ?.

**Comment by jacksutherland** [comment]
Getting the same error. Installed the trial, followed the docs. Entered my API info, clicked save, error. I was running form localhost and am using a free Zoom account. Don't know if that matters.
